version: '3.7'

services:
  db:
    image: mariadb:10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=typo3-dfgviewer-v5
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    #volumes:
    #  - ./volumes/database:/var/lib/mysql
    restart: unless-stopped
  main:
    build: .
    image: kitodo/dfgviewer:5.3
    ports:
      - "0.0.0.0:$PORT:80"
    environment:
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_NAME=typo3-dfgviewer-v5
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - TYPO3_ADMIN_USER=$TYPO3_ADMIN_USER
      - TYPO3_ADMIN_PASSWORD=$TYPO3_ADMIN_PASSWORD
      - TYPO3_ADDITIONAL_CONFIGURATION=$TYPO3_ADDITIONAL_CONFIGURATION
      - HOST=$FullyQualifiedDomainName
    volumes:
      - ./volumes/fileadmin:/var/www/typo3/public/fileadmin/
    depends_on:
      - db
    restart: unless-stopped
